
from colorama import Fore, Back, Style

print(Back.BLUE + "                                                           ")
print(Back.BLUE + Fore.WHITE + "     MARIO                        WORLD           TIME     ")
print(Back.BLUE + Fore.WHITE +  "     00000000        L x 0         1-1                     ")
print(Back.BLUE + "                                                           ")
print(Back.BLUE + "             " + Style.RESET_ALL + Back.BLACK+ "                                 " + Style.RESET_ALL + Back.BLUE + "             " + Style.RESET_ALL  )
print(Back.BLUE + "             " + Style.RESET_ALL + Style.BRIGHT + Back.BLACK+ "      SUPER                      " + Style.RESET_ALL + Back.BLUE + "             " + Style.RESET_ALL  )
print(Back.BLUE + "             " + Style.RESET_ALL + Back.BLACK+ "                                 " + Style.RESET_ALL + Back.BLUE + "             " + Style.RESET_ALL  )
print(Back.BLUE + "             " + Style.RESET_ALL + Back.BLACK+ "                                 " + Style.RESET_ALL + Back.BLUE + "             " + Style.RESET_ALL  )
print(Back.BLUE + "             " + Style.RESET_ALL + Style.BRIGHT + Back.BLACK+ "      MARIO       BROS.          " + Style.RESET_ALL + Back.BLUE + "             " + Style.RESET_ALL  )
print(Back.BLUE + "             " + Style.RESET_ALL + Back.BLACK+ "                                 " + Style.RESET_ALL + Back.BLUE + "             " + Style.RESET_ALL  )
print(Back.BLUE + "             " + Style.RESET_ALL + Back.BLACK+ "                                 " + Style.RESET_ALL + Back.BLUE + "             " + Style.RESET_ALL  )
print(Back.BLUE + "                                                           ")
print(Back.BLUE + "                                                           ")
print(Back.BLUE + "                          START                            ")
print(Back.BLUE + "                                                           ")
print(Back.BLUE + "                      TOP - 0000000                        ")
print(Back.BLUE + "                                                           " + Style.RESET_ALL)
print(Back.BLUE + "            " + Style.RESET_ALL + Back.YELLOW + "  "  +      Back.BLUE + "                                             "  + Style.RESET_ALL)
print(Back.RED + "                                                           " + Style.RESET_ALL)
